name: build
'on':
  push:
    branches:
      - master
jobs:
  net-framework:
    runs-on: windows-latest
    steps:
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2
      - name: Checkout
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
      - name: Restore nuget packages
        run: nuget restore TsakiridisDevicesDaedalos.sln
      - name: Build
        run: >-
          msbuild TsakiridisDevicesDaedalos.sln -p:Configuration=Release -p:UseSharedCompilation=false
      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3
